controller_list:
  - name: fake_mani1_controller
    type: $(arg fake_execution_type)
    joints:
      - mani1_joint1
      - mani1_joint2
      - mani1_joint3
      - mani1_joint4
      - mani1_joint5
      - mani1_joint6
      - mani1_joint7
  - name: fake_mani2_controller
    type: $(arg fake_execution_type)
    joints:
      - mani2_joint1
      - mani2_joint2
      - mani2_joint3
      - mani2_joint4
      - mani2_joint5
      - mani2_joint6
      - mani2_joint7
  - name: fake_body_controller
    type: $(arg fake_execution_type)
    joints:
      - dummy_joint
      - dummy_joint_1
      - dummy_joint_2
initial:  # Define initial robot poses per group
  - group: mani1
    pose: mani1_home
  - group: mani2
    pose: mani2_home
  - group: body
    pose: body_home