# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group:
    - mani1
    - mani2
    - body
  joint_model_group_pose:
    - mani1_home
    - mani2_home
    - body_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - dummy_joint
    - dummy_joint_1
    - dummy_joint_2
    - mani1_joint1
    - mani1_joint2
    - mani1_joint3
    - mani1_joint4
    - mani1_joint5
    - mani1_joint6
    - mani1_joint7
    - mani2_joint1
    - mani2_joint2
    - mani2_joint3
    - mani2_joint4
    - mani2_joint5
    - mani2_joint6
    - mani2_joint7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
dualarm:
  # gazebo_ros_control/pid_gains:
  #   mani1_joint1: {p: 1.0, i: 0.01, d: 100.0}
  #   mani1_joint2: {p: 1.0, i: 0.01, d: 100.0}
  #   mani1_joint3: {p: 1.0, i: 0.01, d: 100.0}
  #   mani1_joint4: {p: 1.0, i: 0.01, d: 100.0}
  #   mani1_joint5: {p: 1.0, i: 0.01, d: 100.0}
  #   mani1_joint6: {p: 1.0, i: 0.01, d: 100.0}
  #   mani1_joint7: {p: 1.0, i: 0.01, d: 100.0}
  #   mani2_joint1: {p: 1.0, i: 0.01, d: 100.0}
  #   mani2_joint2: {p: 1.0, i: 0.01, d: 100.0}
  #   mani2_joint3: {p: 1.0, i: 0.01, d: 100.0}
  #   mani2_joint4: {p: 1.0, i: 0.01, d: 100.0}
  #   mani2_joint5: {p: 1.0, i: 0.01, d: 100.0}
  #   mani2_joint6: {p: 1.0, i: 0.01, d: 100.0}
  #   mani2_joint7: {p: 1.0, i: 0.01, d: 100.0}

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  mani1_controller:
    default: True
    type: position_controllers/JointTrajectoryController
    joints:
      - mani1_joint1
      - mani1_joint2
      - mani1_joint3
      - mani1_joint4
      - mani1_joint5
      - mani1_joint6
      - mani1_joint7
    constraints:
      mani1_joint1: {goal: 0.05}
      mani1_joint2: {goal: 0.05}
      mani1_joint3: {goal: 0.05}
      mani1_joint4: {goal: 0.05}
      mani1_joint5: {goal: 0.05}
      mani1_joint6: {goal: 0.05}
      mani1_joint7: {goal: 0.05}
      stopped_velocity_tolerance: 0

    pid_gains:
      mani1_joint1: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani1_joint2: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani1_joint3: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani1_joint4: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani1_joint5: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani1_joint6: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani1_joint7: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}

  mani2_controller:
    default: True
    type: position_controllers/JointTrajectoryController
    joints:
      - mani2_joint1
      - mani2_joint2
      - mani2_joint3
      - mani2_joint4
      - mani2_joint5
      - mani2_joint6
      - mani2_joint7
    constraints:
      mani2_joint1: {goal: 0.01}
      mani2_joint2: {goal: 0.01}
      mani2_joint3: {goal: 0.01}
      mani2_joint4: {goal: 0.01}
      mani2_joint5: {goal: 0.01}
      mani2_joint6: {goal: 0.01}
      mani2_joint7: {goal: 0.01}
      stopped_velocity_tolerance: 0

    pid_gains:
      mani2_joint1: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani2_joint2: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani2_joint3: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani2_joint4: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani2_joint5: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani2_joint6: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani2_joint7: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}

  body_controller:
    default: True
    type: position_controllers/JointTrajectoryController
    joints:
      - dummy_joint
      - dummy_joint_1
      - dummy_joint_2
    constraints:
      dummy_joint: {goal: 0.01}
      dummy_joint_1: {goal: 0.01}
      dummy_joint_2: {goal: 0.01}
      stopped_velocity_tolerance: 0

    pid_gains:
      dummy_joint: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      dummy_joint_1: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      dummy_joint_2: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}


# mani1_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - mani1_joint1
#     - mani1_joint2
#     - mani1_joint3
#     - mani1_joint4
#     - mani1_joint5
#     - mani1_joint6
#     - mani1_joint7
#   gains:
#     mani1_joint1:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     mani1_joint2:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     mani1_joint3:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     mani1_joint4:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     mani1_joint5:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     mani1_joint6:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     mani1_joint7:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
# mani2_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - mani2_joint1
#     - mani2_joint2
#     - mani2_joint3
#     - mani2_joint4
#     - mani2_joint5
#     - mani2_joint6
#     - mani2_joint7
#   gains:
#     mani2_joint1:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     mani2_joint2:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     mani2_joint3:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     mani2_joint4:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     mani2_joint5:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     mani2_joint6:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     mani2_joint7:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
# body_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - dummy_joint
#   gains:
#     dummy_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1