# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group:
    - manipulator1
    - manipulator2
  joint_model_group_pose: mani1_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - mani1_joint1
    - mani1_joint2
    - mani1_joint3
    - mani1_joint4
    - mani1_joint5
    - mani1_joint6
    - mani1_joint7
    - mani2_joint1
    - mani2_joint2
    - mani2_joint3
    - mani2_joint4
    - mani2_joint5
    - mani2_joint6
    - mani2_joint7
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
dualarm:
#  gazebo_ros_control/pid_gains:
#    mani1_joint1: {p: 1.0, i: 0.01, d: 100.0}
#    mani1_joint2: {p: 1.0, i: 0.01, d: 100.0}
#    mani1_joint3: {p: 1.0, i: 0.01, d: 100.0}
#    mani1_joint4: {p: 1.0, i: 0.01, d: 100.0}
#    mani1_joint5: {p: 1.0, i: 0.01, d: 100.0}
#    mani1_joint6: {p: 1.0, i: 0.01, d: 100.0}
#    mani1_joint7: {p: 1.0, i: 0.01, d: 100.0}
#    mani2_joint1: {p: 1.0, i: 0.01, d: 100.0}
#    mani2_joint2: {p: 1.0, i: 0.01, d: 100.0}
#    mani2_joint3: {p: 1.0, i: 0.01, d: 100.0}
#    mani2_joint4: {p: 1.0, i: 0.01, d: 100.0}
#    mani2_joint5: {p: 1.0, i: 0.01, d: 100.0}
#    mani2_joint6: {p: 1.0, i: 0.01, d: 100.0}
#    mani2_joint7: {p: 1.0, i: 0.01, d: 100.0}

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  manipulator1_controller:
    default: True
    type: "position_controllers/JointTrajectoryController"
    joints:
      - mani1_joint1
      - mani1_joint2
      - mani1_joint3
      - mani1_joint4
      - mani1_joint5
      - mani1_joint6
      - mani1_joint7

    pid_gains:
      mani1_joint1: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani1_joint2: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani1_joint3: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani1_joint4: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani1_joint5: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani1_joint6: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani1_joint7: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}

  manipulator2_controller:
    default: True
    type: "position_controllers/JointTrajectoryController"
    joints:
      - mani2_joint1
      - mani2_joint2
      - mani2_joint3
      - mani2_joint4
      - mani2_joint5
      - mani2_joint6
      - mani2_joint7

    pid_gains:
      mani2_joint1: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani2_joint2: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani2_joint3: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani2_joint4: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani2_joint5: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani2_joint6: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
      mani2_joint7: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#
#  manipulator1_torque:
#    type: effort_controllers/JointEffortController
#    joints:
#      - mani1_joint1
#      - mani1_joint2
#      - mani1_joint3
#      - mani1_joint4
#      - mani1_joint5
#      - mani1_joint6
#      - mani1_joint7
#    pid_gains:
#      mani1_joint1: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#      mani1_joint2: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#      mani1_joint3: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#      mani1_joint4: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#      mani1_joint5: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#      mani1_joint6: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#      mani1_joint7: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#  manipulator2_torque:
#    type: effort_controllers/JointEffortController
#    joints:
#    - mani2_joint1
#    - mani2_joint2
#    - mani2_joint3
#    - mani2_joint4
#    - mani2_joint5
#    - mani2_joint6
#    - mani2_joint7
#    pid_gains:
#      mani2_joint1: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#      mani2_joint2: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#      mani2_joint3: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#      mani2_joint4: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#      mani2_joint5: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#      mani2_joint6: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
#      mani2_joint7: {p: 100.0, i: 1.0, d: 1.0, i_clamp: 1.0}
