// Generated by gencpp from file mservo_msg/joint_queue.msg
// DO NOT EDIT!


#ifndef MSERVO_MSG_MESSAGE_JOINT_QUEUE_H
#define MSERVO_MSG_MESSAGE_JOINT_QUEUE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mservo_msg/joint_data.h>

namespace mservo_msg
{
template <class ContainerAllocator>
struct joint_queue_
{
  typedef joint_queue_<ContainerAllocator> Type;

  joint_queue_()
    : jointq()  {
    }
  joint_queue_(const ContainerAllocator& _alloc)
    : jointq()  {
  (void)_alloc;
      jointq.assign( ::mservo_msg::joint_data_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::mservo_msg::joint_data_<ContainerAllocator> , 2>  _jointq_type;
  _jointq_type jointq;





  typedef boost::shared_ptr< ::mservo_msg::joint_queue_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mservo_msg::joint_queue_<ContainerAllocator> const> ConstPtr;

}; // struct joint_queue_

typedef ::mservo_msg::joint_queue_<std::allocator<void> > joint_queue;

typedef boost::shared_ptr< ::mservo_msg::joint_queue > joint_queuePtr;
typedef boost::shared_ptr< ::mservo_msg::joint_queue const> joint_queueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mservo_msg::joint_queue_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mservo_msg::joint_queue_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mservo_msg::joint_queue_<ContainerAllocator1> & lhs, const ::mservo_msg::joint_queue_<ContainerAllocator2> & rhs)
{
  return lhs.jointq == rhs.jointq;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mservo_msg::joint_queue_<ContainerAllocator1> & lhs, const ::mservo_msg::joint_queue_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mservo_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mservo_msg::joint_queue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mservo_msg::joint_queue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mservo_msg::joint_queue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mservo_msg::joint_queue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mservo_msg::joint_queue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mservo_msg::joint_queue_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mservo_msg::joint_queue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "975ac8b6c2831749c6d3e61906fa26d9";
  }

  static const char* value(const ::mservo_msg::joint_queue_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x975ac8b6c2831749ULL;
  static const uint64_t static_value2 = 0xc6d3e61906fa26d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::mservo_msg::joint_queue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mservo_msg/joint_queue";
  }

  static const char* value(const ::mservo_msg::joint_queue_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mservo_msg::joint_queue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "joint_data[2] jointq\n"
"\n"
"================================================================================\n"
"MSG: mservo_msg/joint_data\n"
"int32[7] pos\n"
;
  }

  static const char* value(const ::mservo_msg::joint_queue_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mservo_msg::joint_queue_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jointq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joint_queue_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mservo_msg::joint_queue_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mservo_msg::joint_queue_<ContainerAllocator>& v)
  {
    s << indent << "jointq[]" << std::endl;
    for (size_t i = 0; i < v.jointq.size(); ++i)
    {
      s << indent << "  jointq[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mservo_msg::joint_data_<ContainerAllocator> >::stream(s, indent + "    ", v.jointq[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSERVO_MSG_MESSAGE_JOINT_QUEUE_H
