// Generated by gencpp from file mservo_msg/joint_data.msg
// DO NOT EDIT!


#ifndef MSERVO_MSG_MESSAGE_JOINT_DATA_H
#define MSERVO_MSG_MESSAGE_JOINT_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mservo_msg
{
template <class ContainerAllocator>
struct joint_data_
{
  typedef joint_data_<ContainerAllocator> Type;

  joint_data_()
    : pos()  {
      pos.assign(0);
  }
  joint_data_(const ContainerAllocator& _alloc)
    : pos()  {
  (void)_alloc;
      pos.assign(0);
  }



   typedef boost::array<int32_t, 7>  _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::mservo_msg::joint_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mservo_msg::joint_data_<ContainerAllocator> const> ConstPtr;

}; // struct joint_data_

typedef ::mservo_msg::joint_data_<std::allocator<void> > joint_data;

typedef boost::shared_ptr< ::mservo_msg::joint_data > joint_dataPtr;
typedef boost::shared_ptr< ::mservo_msg::joint_data const> joint_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mservo_msg::joint_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mservo_msg::joint_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mservo_msg::joint_data_<ContainerAllocator1> & lhs, const ::mservo_msg::joint_data_<ContainerAllocator2> & rhs)
{
  return lhs.pos == rhs.pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mservo_msg::joint_data_<ContainerAllocator1> & lhs, const ::mservo_msg::joint_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mservo_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mservo_msg::joint_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mservo_msg::joint_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mservo_msg::joint_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mservo_msg::joint_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mservo_msg::joint_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mservo_msg::joint_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mservo_msg::joint_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84fce591d749df1cf35b0205dc6eac71";
  }

  static const char* value(const ::mservo_msg::joint_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84fce591d749df1cULL;
  static const uint64_t static_value2 = 0xf35b0205dc6eac71ULL;
};

template<class ContainerAllocator>
struct DataType< ::mservo_msg::joint_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mservo_msg/joint_data";
  }

  static const char* value(const ::mservo_msg::joint_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mservo_msg::joint_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[7] pos\n"
;
  }

  static const char* value(const ::mservo_msg::joint_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mservo_msg::joint_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joint_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mservo_msg::joint_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mservo_msg::joint_data_<ContainerAllocator>& v)
  {
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSERVO_MSG_MESSAGE_JOINT_DATA_H
