// Generated by gencpp from file mservo_msg/traj_1d.msg
// DO NOT EDIT!


#ifndef MSERVO_MSG_MESSAGE_TRAJ_1D_H
#define MSERVO_MSG_MESSAGE_TRAJ_1D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mservo_msg
{
template <class ContainerAllocator>
struct traj_1d_
{
  typedef traj_1d_<ContainerAllocator> Type;

  traj_1d_()
    : traj()  {
      traj.assign(0.0);
  }
  traj_1d_(const ContainerAllocator& _alloc)
    : traj()  {
  (void)_alloc;
      traj.assign(0.0);
  }



   typedef boost::array<double, 7>  _traj_type;
  _traj_type traj;





  typedef boost::shared_ptr< ::mservo_msg::traj_1d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mservo_msg::traj_1d_<ContainerAllocator> const> ConstPtr;

}; // struct traj_1d_

typedef ::mservo_msg::traj_1d_<std::allocator<void> > traj_1d;

typedef boost::shared_ptr< ::mservo_msg::traj_1d > traj_1dPtr;
typedef boost::shared_ptr< ::mservo_msg::traj_1d const> traj_1dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mservo_msg::traj_1d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mservo_msg::traj_1d_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mservo_msg::traj_1d_<ContainerAllocator1> & lhs, const ::mservo_msg::traj_1d_<ContainerAllocator2> & rhs)
{
  return lhs.traj == rhs.traj;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mservo_msg::traj_1d_<ContainerAllocator1> & lhs, const ::mservo_msg::traj_1d_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mservo_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mservo_msg::traj_1d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mservo_msg::traj_1d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mservo_msg::traj_1d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mservo_msg::traj_1d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mservo_msg::traj_1d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mservo_msg::traj_1d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mservo_msg::traj_1d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58e9b5284e3c4cd3c99f99337b97f52c";
  }

  static const char* value(const ::mservo_msg::traj_1d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58e9b5284e3c4cd3ULL;
  static const uint64_t static_value2 = 0xc99f99337b97f52cULL;
};

template<class ContainerAllocator>
struct DataType< ::mservo_msg::traj_1d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mservo_msg/traj_1d";
  }

  static const char* value(const ::mservo_msg::traj_1d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mservo_msg::traj_1d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[7] traj\n"
;
  }

  static const char* value(const ::mservo_msg::traj_1d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mservo_msg::traj_1d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct traj_1d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mservo_msg::traj_1d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mservo_msg::traj_1d_<ContainerAllocator>& v)
  {
    s << indent << "traj[]" << std::endl;
    for (size_t i = 0; i < v.traj.size(); ++i)
    {
      s << indent << "  traj[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.traj[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSERVO_MSG_MESSAGE_TRAJ_1D_H
